baseURL = ""
languageCode = "en-us"
title = "Advanced Microcontrols, Inc."
theme = "grayscale"
[Params]
    # Provide some metadata for search and indexing services
    description = "A port of the Grayscale theme to Hugo"
    author = "RunningStream"
